<?php
namespace App\Services;

use RuntimeException;

final class AiVideoPlanningService
{
    public function createPlan(int $ownerId,string $provider,string $transcript,string $instructions,string $aspectRatio,string $captionStyle,string $logoUrl='',string $stylePreset='vnv_premium',array $assets=[]): array
    {
        if(trim($transcript)==='')throw new RuntimeException('Generate or enter a transcript first.');
        $provider='openai';
        $shape=['summary'=>'','hook_options'=>[],'cuts'=>[['start'=>'00:00:00','end'=>'00:00:10','reason'=>'']],'jump_cut_notes'=>[],'caption_notes'=>[],'caption_animation'=>['preset'=>'word_pop','timing'=>'word_by_word','emphasis_words'=>[]],'camera_moves'=>[['start'=>'00:00:00','end'=>'00:00:02','type'=>'punch_in|punch_out|slow_push|reframe','zoom'=>1.08,'focus_x'=>0.5,'focus_y'=>0.42,'reason'=>'']],'transitions'=>[['timestamp'=>'00:00:03','type'=>'blur|flash|dip_to_black|whip_left|whip_right|soft_fade','duration'=>0.18,'reason'=>'']],'motion_graphics'=>[['timestamp'=>'','type'=>'callout|chart|icon|stat','content'=>'','animation'=>'']],'generated_inserts'=>[['start'=>'00:00:00','duration_seconds'=>3,'prompt'=>'','asset_name'=>'exact relative path when using an uploaded project file','asset_url'=>'exact approved asset URL or empty for an explicitly requested generation','mime_type'=>'video/* or image/*','media_type'=>'generated_video|generated_image|uploaded_asset','status'=>'PROPOSED']],'trend_adaptation'=>['format'=>'','why_it_fits'=>'','avoid_copying'=>true],'color_notes'=>[],'audio_notes'=>[],'sound_effect_cues'=>[],'intro'=>['duration_seconds'=>0,'animation'=>'','logo_treatment'=>''],'outro'=>['duration_seconds'=>0,'call_to_action'=>'','logo_treatment'=>''],'b_roll_prompts'=>[],'thumbnail_concepts'=>[['headline'=>'','composition'=>'','colors'=>[]]],'platform_copy'=>['youtube_title'=>'','youtube_description'=>'','short_caption'=>'','hashtags'=>[]],'export'=>['aspect_ratio'=>$aspectRatio,'caption_style'=>$captionStyle]];
        $presetNotes=$stylePreset==='marketing_educator'?'Fast, concise educational marketing video: immediate hook, confident talking-head pacing, purposeful jump cuts, high-contrast VNV teal/white/charcoal graphics, large readable captions, animated statistics and charts, clear CTA. Do not copy Neil Patel branding, wording, likeness or exact compositions.':'Premium VNV Events editorial video: polished, energetic, elegant, brand-consistent and emotionally warm.';
        $plan=(new AiModelGateway())->json($ownerId,$provider,'You are a senior VNV Events video editor. Produce a non-destructive, human-reviewable plan only. Never invent timestamps beyond the transcript. Never choose random media: reference only exact supplied asset URLs/names, unless the user explicitly requested generating a missing visual. A transition is only blur, flash, dip_to_black, whip_left, whip_right or soft_fade; it must never create a camera move. Keep zooms exclusively in camera_moves with an explicit focus and intensity. Adapt current format signals without copying protected creative. Preserve the supplied logo. Make every change feel motivated by speech, gaze, gesture, musical beat or a real scene boundary. Preserve conversational breathing room; do not cut tightly against phonemes. Prefer clean editorial cuts over decorative flashes. Use subtle 1.04-1.10 punch-ins, hold them long enough to feel intentional, and return smoothly. Never stack a transition and camera move at the same timestamp. Captions may use word-by-word kinetic emphasis.',['transcript'=>mb_substr($transcript,0,45000),'instructions'=>$instructions,'style_preset'=>$stylePreset,'preset_direction'=>$presetNotes,'aspect_ratio'=>$aspectRatio,'caption_style'=>$captionStyle,'logo_url'=>$logoUrl,'approved_assets'=>$assets,'current_public_video_signals'=>(new AiTrendService())->currentVideoSignals()],$shape);
        $plan['_request']=['provider'=>$provider,'instructions'=>$instructions,'style_preset'=>$stylePreset,'aspect_ratio'=>$aspectRatio,'caption_style'=>$captionStyle,'logo_url'=>$logoUrl,
            'intro_url'=>(string)($assets['intro_url']??''),'outro_url'=>(string)($assets['outro_url']??''),'overlay_url'=>(string)($assets['overlay_url']??''),'audio_url'=>(string)($assets['audio_url']??''),'generated_at'=>date('c')];return $plan;
    }
}
