<?php
namespace App\Services;

use App\Repositories\Connection;
use App\Utils\LocationUtils;
use RuntimeException;

final class MochiServiceCatalogWorkflowService
{
    private const START_RE='/\b(agregar|crear|nuevo|modificar|editar|actualizar|add|create|modify|edit|update)\b.*\b(servicio|service)\b|\b(servicio|service)\b.*\b(agregar|crear|modificar|editar|add|create|modify|edit)\b/iu';
    private const YES_RE='/^(s[ií]|yes|correcto|aprobado|approve|hazlo|créalo|crealo)[.!\s]*$/iu';
    public function __construct(private int $ownerId=2,private string $siteKey='vnvevents',private ?Connection $db=null){$this->db??=new Connection();}
    public function active(int $user,int $session): ?object {$this->db->query("SELECT * FROM mochi_service_workflows WHERE id_owner=:owner AND site_key=:site AND id_user=:user AND id_session=:session AND status NOT IN ('COMPLETED','CANCELLED') LIMIT 1");$this->bind(['owner'=>$this->ownerId,'site'=>$this->siteKey,'user'=>$user,'session'=>$session]);return $this->db->fetchOne()?:null;}
    public function shouldHandle(int $user,int $session,string $message): bool{return (bool)($this->active($user,$session)||preg_match(self::START_RE,$message));}
    public function handle(int $user,int $level,int $session,string $message): array
    {
        if($level!==1)throw new RuntimeException('Este workflow está disponible únicamente para Level 1.');$w=$this->active($user,$session);
        if(preg_match('/\b(cancelar|cancel|salir)\b/iu',$message)){if($w)$this->status((int)$w->id,'CANCELLED');return $this->result('Cancelé el borrador; no cambié ningún servicio ni producto.',null);}
        if(!$w){$w=$this->create($user,$session);if($this->starterOnly($message))return $this->result('Perfecto. Dime el nombre del servicio y si deseas crearlo o modificarlo. Si ya existe, te mostraré su descripción y precio actuales antes de cambiar nada.',$w);}
        $d=$this->decode($w->draft_json);
        if($w->status==='ASK_STORE'){
            if(preg_match('/\b(no|solo servicio|not now)\b/iu',$message)){$this->status((int)$w->id,'COMPLETED');return $this->result('Listo para usarse en estimates ✅ El servicio quedó guardado y no se creó ningún producto de tienda.',$this->reload((int)$w->id),$this->serviceItems((int)$w->current_service_id));}
            if(preg_match('/\b(s[ií]|yes|tienda|store)\b/iu',$message)){$d['publish_store']=true;$this->save((int)$w->id,$d,'COLLECTING');return $this->result('Perfecto. Dime la categoría de la tienda y el estilo que quieres para la imagen. También puedes corregir el texto público, precio o tiempo de preparación.',$this->reload((int)$w->id));}
        }
        if($w->status==='REVIEW_SERVICE'&&preg_match(self::YES_RE,trim($message)))return $this->saveService($w,$d,$user);
        if($w->status==='REVIEW_STORE'&&preg_match(self::YES_RE,trim($message)))return $this->saveStoreProduct($w,$d,$user);
        $mentioned=empty($d['service_id'])?$this->mentionedService($message):null;$p=$this->parse($d,$message);if($mentioned)$p['service_identifier']=(string)$mentioned->id;$explicitStore=(bool)preg_match('/\b(tienda|store|públic[oa]|publicar|publish)\b/iu',$message);if(empty($d['publish_store'])&&!$explicitStore){unset($p['publish_store'],$p['store_category'],$p['image_style'],$p['short_description'],$p['lead_hours']);}$d=array_replace($d,array_filter($p,fn($v)=>$v!==null&&$v!==''));
        if(empty($d['service_id'])&&!empty($d['service_identifier'])){if($existing=$this->findService((string)$d['service_identifier'])){$d['service_id']=(int)$existing->id;$d['operation']='MODIFY';if($mentioned&&!preg_match('/\b(rename|renombrar|cambiar (?:el )?nombre|llamarlo)\b/iu',$message))$d['name']=$existing->name;else $d['name']=$d['name']??$existing->name;$d['description']=$d['description']??$existing->description;$d['price']=$d['price']??(float)$existing->price;$d['requirements']=$d['requirements']??$existing->requirements;$d['current']=['name'=>$existing->name,'description'=>$existing->description,'price'=>(float)$existing->price,'requirements'=>$existing->requirements];}}
        if(!empty($d['publish_store'])){
            $missing=[];foreach(['name'=>'nombre','description'=>'descripción pública','price'=>'precio','store_category'=>'categoría','image_style'=>'estilo de imagen'] as $k=>$label)if(empty($d[$k]))$missing[]=$label;$this->save((int)$w->id,$d,$missing?'COLLECTING':'REVIEW_STORE');
            if($missing)return $this->result($this->summary($d)."\n\nPara preparar el producto de tienda necesito: ".implode(', ',$missing).'.',$this->reload((int)$w->id));
            return $this->result($this->summary($d)."\n\nCrearé el producto en DRAFT, generaré una imagen con IA en el estilo indicado y lo asociaré con esa categoría. ¿Confirmas?",$this->reload((int)$w->id));
        }
        $missing=[];foreach(['name'=>'nombre','description'=>'descripción','price'=>'precio'] as $k=>$label)if(!isset($d[$k])||$d[$k]==='')$missing[]=$label;$this->save((int)$w->id,$d,$missing?'COLLECTING':'REVIEW_SERVICE');
        if($missing)return $this->result($this->summary($d)."\n\nNecesito: ".implode(', ',$missing).'. También puedes indicar requisitos o si el precio es por invitado.',$this->reload((int)$w->id));
        return $this->result($this->summary($d)."\n\n¿Confirmas que guarde este servicio?",$this->reload((int)$w->id));
    }
    private function parse(array $current,string $message): array {try{return (new AiJsonGenerator())->generate('Update a VNV Events service/catalog draft from the latest Spanish or English message. Preserve current values unless corrected. Service and customer-facing copy must be English. Never invent price or facts. Return JSON only.',['current'=>$current,'message'=>$message],['operation'=>'CREATE or MODIFY or null','service_identifier'=>'existing service name or id or null','name'=>'English service name or null','description'=>'detailed English description or null','price'=>'number or null','requirements'=>'English operational requirements or null','is_variable'=>'boolean or null','publish_store'=>'boolean or null','store_category'=>'category name or slug or null','image_style'=>'visual style requested by user or null','short_description'=>'concise English public description or null','lead_hours'=>'integer or null']);}catch(\Throwable){return [];}}
    private function findService(string $q): ?object {$id=ctype_digit(trim($q))?(int)$q:0;$this->db->query('SELECT * FROM orders_services WHERE id_owner=:owner AND is_archived=0 AND ((:id>0 AND id=:id) OR LOWER(name)=LOWER(:q) OR LOWER(name) LIKE LOWER(:like)) ORDER BY LOWER(name)=LOWER(:q) DESC LIMIT 1');$this->bind(['owner'=>$this->ownerId,'id'=>$id,'q'=>$q,'like'=>'%'.$q.'%']);return $this->db->fetchOne()?:null;}
    private function mentionedService(string $message): ?object {$this->db->query('SELECT * FROM orders_services WHERE id_owner=:owner AND is_archived=0 ORDER BY CHAR_LENGTH(name) DESC');$this->db->bind(':owner',$this->ownerId);foreach($this->db->fetchAll() as $service)if(mb_stripos($message,(string)$service->name)!==false)return $service;return null;}
    private function saveService(object $w,array $d,int $user): array {$before=$d['current']??null;if($w->current_service_id||!empty($d['service_id'])){$id=(int)($w->current_service_id?:$d['service_id']);$this->db->query('UPDATE orders_services SET name=:name,description=:description,price=:price,requirements=:requirements,is_variable=:variable WHERE id=:id AND id_owner=:owner');$this->bind(['name'=>$d['name'],'description'=>$d['description'],'price'=>(float)$d['price'],'requirements'=>$d['requirements']??null,'variable'=>!empty($d['is_variable'])?'YES':'NO','id'=>$id,'owner'=>$this->ownerId]);$this->db->execute();$action='UPDATE_SERVICE';}else{$this->db->query("INSERT INTO orders_services(name,description,price,requirements,id_owner,is_archived,is_variable) VALUES(:name,:description,:price,:requirements,:owner,0,:variable)");$this->bind(['name'=>$d['name'],'description'=>$d['description'],'price'=>(float)$d['price'],'requirements'=>$d['requirements']??null,'owner'=>$this->ownerId,'variable'=>!empty($d['is_variable'])?'YES':'NO']);$this->db->execute();$id=(int)$this->db->lastId();$action='CREATE_SERVICE';}$this->save((int)$w->id,$d,'ASK_STORE',$id);$this->audit($user,$action,'service',$id,['before'=>$before,'after'=>$d]);return $this->result("Listo para usarse en estimates ✅ Servicio #{$id}: {$d['name']} — $".number_format((float)$d['price'],2).".\n\n¿Quieres agregarlo también a la tienda pública?",$this->reload((int)$w->id),$this->serviceItems($id));}
    private function saveStoreProduct(object $w,array $d,int $user): array {$category=$this->category((string)$d['store_category']);$prompt="Square catalog product image for VNV Events: {$d['name']}. {$d['description']}. Requested visual style: {$d['image_style']}. Elegant premium South Florida event presentation, product clearly visible, no text, no logo, no watermark.";$image=(new CmsImageGenerationService())->generateAndUploadWithRetry($prompt,'store/products/generated','1024x1024',2);$slug=$this->slug((string)$d['name']).'-'.date('ymdHis');$sku='MOCHI-'.strtoupper(substr(hash('sha256',$slug),0,10));$this->db->query("INSERT INTO store_products(id_owner,site_key,name,slug,sku,brand_name,short_description,description,product_type,purchase_mode,allow_immediate_payment,allow_recurring_purchase,fulfillment_type,product_role,is_addon_only,lead_hours,price,currency_code,main_image,stock_quantity,min_purchase_qty,is_featured,is_public,status,created_at,updated_at) VALUES(:owner,:site,:name,:slug,:sku,'VNV Events',:short,:description,'FIXED','REQUEST',0,0,'SERVICE','MAIN',0,:lead,:price,'USD',:image,0,1,0,0,'DRAFT',NOW(),NOW())");$this->bind(['owner'=>$this->ownerId,'site'=>$this->siteKey,'name'=>$d['name'],'slug'=>$slug,'sku'=>$sku,'short'=>$d['short_description']??mb_substr(strip_tags((string)$d['description']),0,480),'description'=>'<p>'.htmlspecialchars((string)$d['description'],ENT_QUOTES,'UTF-8').'</p>','lead'=>max(0,(int)($d['lead_hours']??24)),'price'=>(float)$d['price'],'image'=>$image['url']]);$this->db->execute();$product=(int)$this->db->lastId();$this->db->query('INSERT INTO store_products_categories(id_owner,id_product,id_category) VALUES(:owner,:product,:category)');$this->bind(['owner'=>$this->ownerId,'product'=>$product,'category'=>(int)$category->id]);$this->db->execute();$this->save((int)$w->id,$d,'COMPLETED',(int)$w->current_service_id,$product);$this->audit($user,'CREATE_STORE_PRODUCT_DRAFT','store_product',$product,['service_id'=>(int)$w->current_service_id,'category_id'=>(int)$category->id,'image'=>$image]);$items=$this->serviceItems((int)$w->current_service_id);$items[]=['title'=>'Producto DRAFT #'.$product,'meta'=>$category->name,'detail'=>'Imagen IA lista · no público','url'=>LocationUtils::pathFor('panel/planner-hub/store/products/edit?id='.$product)];return $this->result("Producto #{$product} creado en DRAFT con imagen IA y categoría {$category->name}. No está visible al público hasta aprobación. El servicio está listo para estimates ✅",$this->reload((int)$w->id),$items);}
    private function category(string $q): object {$this->db->query('SELECT * FROM store_categories WHERE id_owner=:owner AND site_key=:site AND status=\'ACTIVE\' AND (LOWER(name)=LOWER(:q) OR LOWER(slug)=LOWER(:q) OR LOWER(name) LIKE LOWER(:like)) ORDER BY LOWER(name)=LOWER(:q) DESC LIMIT 1');$this->bind(['owner'=>$this->ownerId,'site'=>$this->siteKey,'q'=>$q,'like'=>'%'.$q.'%']);$c=$this->db->fetchOne();if(!$c)throw new RuntimeException('No encontré esa categoría activa. Dime otra categoría antes de crear el producto.');return $c;}
    private function summary(array $d): string {$text="Servicio\n".($d['name']??'—')."\nPrecio: ".(isset($d['price'])?'$'.number_format((float)$d['price'],2):'—')."\nDescripción: ".($d['description']??'—')."\nRequisitos: ".($d['requirements']??'—');if(!empty($d['current']))$text="Datos actuales\n{$d['current']['name']}\n$".number_format((float)$d['current']['price'],2)."\n{$d['current']['description']}\n\nPropuesta\n".$text;if(!empty($d['publish_store']))$text.="\n\nTienda\nCategoría: ".($d['store_category']??'—')."\nEstilo de imagen: ".($d['image_style']??'—')."\nEstado inicial: DRAFT";return $text;}
    private function serviceItems(int $id): array {return [['title'=>'Servicio #'.$id,'meta'=>'Listo para estimates','detail'=>'Abrir servicios','url'=>LocationUtils::pathFor('panel/planner-hub/management/orders/services')]];}
    private function starterOnly(string $m): bool {$p=mb_strtolower(trim(preg_replace('/[^\pL\pN\s]+/u',' ',$m)??$m));return in_array($p,['quiero agregar o modificar un servicio','agregar o modificar servicio','add or modify a service'],true);}
    private function slug(string $v): string {$v=iconv('UTF-8','ASCII//TRANSLIT//IGNORE',$v)?:$v;$v=strtolower(preg_replace('/[^a-zA-Z0-9]+/','-',$v)??$v);return trim($v,'-')?:'service';}
    private function create(int $u,int $s): object {$this->db->query("INSERT INTO mochi_service_workflows(id_owner,site_key,id_user,id_session,status,draft_json) VALUES(:owner,:site,:user,:session,'COLLECTING','{}') ON DUPLICATE KEY UPDATE status='COLLECTING',draft_json='{}',current_service_id=NULL,current_product_id=NULL");$this->bind(['owner'=>$this->ownerId,'site'=>$this->siteKey,'user'=>$u,'session'=>$s]);$this->db->execute();return $this->active($u,$s);}
    private function save(int $id,array $d,string $status,?int $service=null,?int $product=null): void {$this->db->query('UPDATE mochi_service_workflows SET draft_json=:draft,status=:status,current_service_id=COALESCE(:service,current_service_id),current_product_id=COALESCE(:product,current_product_id) WHERE id=:id');$this->bind(['draft'=>json_encode($d,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES),'status'=>$status,'service'=>$service,'product'=>$product,'id'=>$id]);$this->db->execute();}
    private function status(int $id,string $s): void {$this->db->query('UPDATE mochi_service_workflows SET status=:status WHERE id=:id');$this->bind(['status'=>$s,'id'=>$id]);$this->db->execute();}
    private function reload(int $id): object {$this->db->query('SELECT * FROM mochi_service_workflows WHERE id=:id');$this->db->bind(':id',$id);return $this->db->fetchOne();}
    private function decode(string $j): array{return json_decode($j,true)?:[];}
    private function audit(int $u,string $a,string $type,int $id,array $f): void {$this->db->query("INSERT INTO mochi_action_audit(id_owner,site_key,id_user,action_key,entity_type,entity_id,action_source,fields_json,status) VALUES(:owner,:site,:user,:action,:type,:entity,'MOCHI',:fields,'SUCCEEDED')");$this->bind(['owner'=>$this->ownerId,'site'=>$this->siteKey,'user'=>$u,'action'=>$a,'type'=>$type,'entity'=>(string)$id,'fields'=>json_encode($f,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)]);$this->db->execute();}
    private function result(string $reply,?object $w,array $items=[]): array{return ['reply'=>$reply,'items'=>$items,'service_workflow'=>$w?['id'=>(int)$w->id,'status'=>$w->status,'current_service_id'=>$w->current_service_id? (int)$w->current_service_id:null,'current_product_id'=>$w->current_product_id? (int)$w->current_product_id:null]:null];}
    private function bind(array $v): void {foreach($v as $k=>$x)$this->db->bind(':'.$k,$x);}
}
