<?php
namespace App\Services;

use App\Repositories\ClientsUsersRepository;
use App\Repositories\Connection;
use App\Repositories\NotificationsRepository;
use App\Repositories\OrdersRepository;

final class MochiActionService
{
    private const ACTIONS=['CREATE_CUSTOMER','UPDATE_CUSTOMER','CREATE_ESTIMATE','CREATE_ORDER','CREATE_EVENT','ADD_NOTE','CREATE_FOLLOW_UP','ASSOCIATE_REQUEST_CUSTOMER','ASSOCIATE_CUSTOMER_ORDER','SEND_CUSTOMER_EMAIL','SEND_PUSH_NOTIFICATION'];
    public function __construct(private int $ownerId,private string $siteKey='vnvevents',private ?Connection $db=null){$this->db??=new Connection();}
    public function detects(string $message): bool {return (bool)preg_match('/\b(crea|crear|create|actualiza|update|agrega|añade|nota|seguimiento|follow.?up|asocia|associate|env[ií]a|send)\b/iu',$message);}

    public function prepare(int $userId,int $level,int $sessionId,string $message): array
    {
        $this->assertAdmin($level);$parsed=$this->parse($message);$action=(string)($parsed['action']??'UNKNOWN');if(!in_array($action,self::ACTIONS,true))return ['reply'=>'Puedo crear o actualizar clientes, crear estimates/órdenes/eventos, agregar notas o follow-ups, asociar registros y enviar email o push. Dime exactamente qué deseas hacer.','items'=>[]];
        $payload=is_array($parsed['fields']??null)?$parsed['fields']:[];$payload=$this->resolveCustomerIdentity($action,$payload);$missing=$this->validate($action,$payload);$duplicates=$missing?[]:$this->duplicates($action,$payload);
        if($missing)return ['reply'=>'Para preparar la acción necesito: '.implode(', ',$missing).'.','items'=>[],'action_key'=>$action];
        if($duplicates)return ['reply'=>'Encontré posibles duplicados. No preparé la acción todavía. Confirma el ID correcto o explícame si realmente es un registro nuevo.','items'=>$duplicates,'action_key'=>$action];
        $summary=$this->summary($action,$payload);$this->db->query("INSERT INTO mochi_action_drafts(id_owner,site_key,id_user,id_session,action_key,payload_json,summary,expires_at) VALUES(:owner,:site,:user,:session,:action,:payload,:summary,DATE_ADD(UTC_TIMESTAMP(),INTERVAL 30 MINUTE))");$this->bind(['owner'=>$this->ownerId,'site'=>$this->siteKey,'user'=>$userId,'session'=>$sessionId,'action'=>$action,'payload'=>json_encode($payload,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES),'summary'=>$summary]);$this->db->execute();$id=(int)$this->db->lastId();return ['reply'=>'Revisa antes de confirmar: '.$summary,'items'=>[],'action_draft'=>['id'=>$id,'action'=>$action,'summary'=>$summary]];
    }

    public function execute(int $draftId,int $userId,int $level): array
    {
        $this->assertAdmin($level);$action='UNKNOWN';$payload=[];$this->db->beginTransaction();try{$this->db->query("SELECT * FROM mochi_action_drafts WHERE id=:id AND id_owner=:owner AND site_key=:site AND id_user=:user AND status='PENDING' AND expires_at>UTC_TIMESTAMP() FOR UPDATE");$this->bind(['id'=>$draftId,'owner'=>$this->ownerId,'site'=>$this->siteKey,'user'=>$userId]);$draft=$this->db->fetchOne();if(!$draft)throw new \RuntimeException('La acción ya no está disponible o expiró.');$payload=json_decode((string)$draft->payload_json,true)?:[];$action=(string)$draft->action_key;$this->db->query("UPDATE mochi_action_drafts SET status='CONFIRMED',confirmed_at=UTC_TIMESTAMP() WHERE id=:id AND status='PENDING'");$this->db->bind(':id',$draftId);$this->db->execute();$result=$this->perform($action,$payload,$userId);$this->db->query("UPDATE mochi_action_drafts SET status='EXECUTED',executed_at=UTC_TIMESTAMP(),result_json=:result WHERE id=:id");$this->db->bind(':result',json_encode($result,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES));$this->db->bind(':id',$draftId);$this->db->execute();$this->audit($draftId,$userId,$action,$result['entity_type'],$result['entity_id'],$payload,'SUCCEEDED');$this->db->commit();return $result;
        }catch(\Throwable $e){$this->db->rollback();$this->audit($draftId,$userId,$action,'unknown',null,$payload,'FAILED','EXECUTION_FAILED');error_log('[Mochi action '.$action.'] '.$e->getMessage());throw new \RuntimeException('No pude completar la acción. No se aplicaron cambios.');}
    }
    public function cancel(int $draftId,int $userId): void {$this->db->query("UPDATE mochi_action_drafts SET status='CANCELLED' WHERE id=:id AND id_owner=:owner AND site_key=:site AND id_user=:user AND status='PENDING'");$this->bind(['id'=>$draftId,'owner'=>$this->ownerId,'site'=>$this->siteKey,'user'=>$userId]);$this->db->execute();$this->audit($draftId,$userId,'CANCEL','action_draft',(string)$draftId,[],'CANCELLED');}

    private function parse(string $message): array {try{return (new AiJsonGenerator())->generate('Extract one controlled VNV write action. Never infer missing values. Dates must be YYYY-MM-DD and times HH:MM:SS. Allowed actions: '.implode(',',self::ACTIONS).'. Fields may include customer_id, request_id, order_id, full_name, email, phone, address, event_date, start_time, end_time, service_id, quantity, note, due_at, subject, body.',['message'=>$message],['action'=>'allowed action or UNKNOWN','fields'=>['only explicitly supplied normalized fields']]);}catch(\Throwable){return ['action'=>'UNKNOWN','fields'=>[]];}}
    private function validate(string $a,array $p): array {$required=match($a){'CREATE_CUSTOMER'=>['full_name','email'],'UPDATE_CUSTOMER'=>['customer_id'],'CREATE_ESTIMATE','CREATE_ORDER','CREATE_EVENT'=>['email','event_date'],'ADD_NOTE'=>['order_id','note'],'CREATE_FOLLOW_UP'=>['customer_id','due_at','subject'],'ASSOCIATE_REQUEST_CUSTOMER'=>['request_id','customer_id'],'ASSOCIATE_CUSTOMER_ORDER'=>['order_id','customer_id'],'SEND_CUSTOMER_EMAIL'=>['customer_id','subject','body'],'SEND_PUSH_NOTIFICATION'=>['customer_id','subject','body'],default=>[]};$missing=[];foreach($required as $f)if(!isset($p[$f])||trim((string)$p[$f])==='')$missing[]=$this->fieldLabel($f);if(in_array($a,['CREATE_ESTIMATE','CREATE_ORDER','CREATE_EVENT'],true)&&empty($p['customer_id'])&&empty($p['full_name']))$missing[]='nombre del cliente';if(isset($p['email'])&&!filter_var($p['email'],FILTER_VALIDATE_EMAIL))$missing[]='correo válido del cliente';if(isset($p['event_date'])&&!preg_match('/^\d{4}-\d{2}-\d{2}$/',(string)$p['event_date']))$missing[]='fecha del evento';return array_values(array_unique($missing));}
    private function resolveCustomerIdentity(string $action,array $payload): array {if(!in_array($action,['CREATE_ESTIMATE','CREATE_ORDER','CREATE_EVENT'],true))return $payload;$email=trim((string)($payload['email']??''));if(!filter_var($email,FILTER_VALIDATE_EMAIL))return $payload;$this->db->query('SELECT id,name,lastname,email FROM users WHERE id_owner=:owner AND level=5 AND is_active=1 AND LOWER(email)=LOWER(:email) LIMIT 1');$this->bind(['owner'=>$this->ownerId,'email'=>$email]);if($customer=$this->db->fetchOne()){$payload['customer_id']=(int)$customer->id;$payload['full_name']=trim($customer->name.' '.$customer->lastname);}return $payload;}
    private function fieldLabel(string $field): string {return ['customer_id'=>'cliente','event_date'=>'fecha del evento','email'=>'correo del cliente','full_name'=>'nombre del cliente','request_id'=>'solicitud','order_id'=>'orden o estimate','note'=>'nota','due_at'=>'fecha de seguimiento','subject'=>'asunto','body'=>'mensaje'][$field]??'dato necesario';}
    private function duplicates(string $a,array $p): array {if($a==='CREATE_CUSTOMER'){$this->db->query("SELECT id,name,lastname,email,phone FROM users WHERE id_owner=:owner AND level=5 AND (LOWER(email)=LOWER(:email) OR (:phone<>'' AND phone=:phone) OR LOWER(CONCAT_WS(' ',name,lastname))=LOWER(:name)) LIMIT 5");$this->bind(['owner'=>$this->ownerId,'email'=>(string)$p['email'],'phone'=>(string)($p['phone']??''),'name'=>(string)$p['full_name']]);return array_map(fn($r)=>['title'=>'Cliente #'.$r->id.' · '.trim($r->name.' '.$r->lastname),'meta'=>$r->email,'detail'=>(string)$r->phone,'url'=>'/panel/planner-hub/management/users/edit?id='.$r->id],$this->db->fetchAll());}if(in_array($a,['CREATE_ESTIMATE','CREATE_ORDER','CREATE_EVENT'],true)){$this->db->query("SELECT id,event_date,status_workflow,address FROM orders WHERE id_owner=:owner AND id_client=:customer AND event_date=:day AND COALESCE(is_archived,0)=0 LIMIT 5");$this->bind(['owner'=>$this->ownerId,'customer'=>(int)$p['customer_id'],'day'=>$p['event_date']]);return array_map(fn($r)=>['title'=>'Orden/evento #'.$r->id,'meta'=>$r->event_date.' · '.$r->status_workflow,'detail'=>(string)$r->address,'url'=>'/panel/planner-hub/management/orders/orders/edit?id='.$r->id],$this->db->fetchAll());}if($a==='UPDATE_CUSTOMER'&&!empty($p['email'])){$this->db->query("SELECT id,name,lastname,email FROM users WHERE id_owner=:owner AND level=5 AND id<>:id AND LOWER(email)=LOWER(:email) LIMIT 5");$this->bind(['owner'=>$this->ownerId,'id'=>(int)$p['customer_id'],'email'=>$p['email']]);return array_map(fn($r)=>['title'=>'Cliente #'.$r->id.' · '.trim($r->name.' '.$r->lastname),'meta'=>$r->email,'detail'=>'Ese email ya pertenece a otro cliente','url'=>'/panel/planner-hub/management/users/edit?id='.$r->id],$this->db->fetchAll());}return [];}
    private function perform(string $a,array $p,int $actor): array
    {
        if($a==='CREATE_CUSTOMER'){$u=StoreCustomerService::findOrCreateLevel5User($this->ownerId,(string)$p['full_name'],(string)$p['email'],(string)($p['phone']??''));if(!$u)throw new \RuntimeException('Customer create failed.');(new ClientsUsersRepository())->create((int)$u->id,$this->ownerId);return $this->result('customer',(int)$u->id,trim($u->name.' '.$u->lastname),'/panel/planner-hub/management/users/edit?id='.$u->id);}
        if($a==='UPDATE_CUSTOMER'){
            $customer=$this->customer((int)$p['customer_id']);$allowed=[];foreach(['full_name','email','phone'] as $f)if(isset($p[$f]))$allowed[$f]=$p[$f];$fields=[];
            if(isset($allowed['full_name'])){[$fields['name'],$fields['lastname']]=array_pad(preg_split('/\s+/',trim((string)$allowed['full_name']),2),2,'');}
            foreach(['email','phone'] as $f)if(isset($allowed[$f]))$fields[$f]=$allowed[$f];
            if(isset($fields['email'])){$fields['email']=strtolower(trim((string)$fields['email']));if(!filter_var($fields['email'],FILTER_VALIDATE_EMAIL))throw new \RuntimeException('Invalid customer email.');$this->db->query("SELECT id FROM users WHERE id<>:id AND LOWER(email)=LOWER(:email) LIMIT 1");$this->bind(['id'=>(int)$customer->id,'email'=>$fields['email']]);if($this->db->fetchOne())throw new \RuntimeException('That email is already registered to another account.');}
            if(!$fields)throw new \RuntimeException('No contact fields supplied.');$set=[];foreach($fields as $k=>$v)$set[]="{$k}=:{$k}";$this->db->query("UPDATE users SET ".implode(',',$set)." WHERE id=:id AND id_owner=:owner AND level=5");foreach($fields as $k=>$v)$this->db->bind(':'.$k,$v);$this->bind(['id'=>(int)$customer->id,'owner'=>$this->ownerId]);$this->db->execute();
            if(isset($fields['email'])){$this->db->query("UPDATE crm_leads SET email=:email WHERE id_owner=:owner AND (id_user=:customer OR (id_user IS NULL AND LOWER(email)=LOWER(:old_email)))");$this->bind(['email'=>$fields['email'],'owner'=>$this->ownerId,'customer'=>(int)$customer->id,'old_email'=>(string)$customer->email]);$this->db->execute();}
            return $this->result('customer',(int)$customer->id,'Contacto actualizado','/panel/planner-hub/management/users/edit?id='.$customer->id);
        }
        if(in_array($a,['CREATE_ESTIMATE','CREATE_ORDER','CREATE_EVENT'],true)){ $customerId=(int)($p['customer_id']??0);if(!$customerId){$customer=StoreCustomerService::findOrCreateLevel5User($this->ownerId,(string)($p['full_name']??''),(string)$p['email'],(string)($p['phone']??''));if(!$customer)throw new \RuntimeException('No pude crear el cliente.');$customerId=(int)$customer->id;}(new ClientsUsersRepository())->create($customerId,$this->ownerId);$this->customer($customerId);$orderId=(new OrdersRepository())->addWithExplicitOwner(['id_owner'=>$this->ownerId,'id_user'=>$actor,'id_client'=>$customerId,'event_date'=>$p['event_date'],'address'=>(string)($p['address']??''),'start_time'=>(string)($p['start_time']??'18:00:00'),'end_time'=>(string)($p['end_time']??'22:00:00'),'payment_status'=>'pending','status_workflow'=>'INVOICE_DRAFT','notes'=>'Created by Mochi for review.','payment_split_type'=>2,'payment_split_percent_1'=>50,'payment_split_percent_2'=>50,'total_team_needed'=>0,'is_archived'=>0]);if(!$orderId)throw new \RuntimeException('Order create failed.');if(!empty($p['service_id'])){$this->db->query("SELECT id,price,description FROM orders_services WHERE id=:id AND id_owner=:owner AND is_archived=0");$this->bind(['id'=>(int)$p['service_id'],'owner'=>$this->ownerId]);$s=$this->db->fetchOne();if(!$s)throw new \RuntimeException('Service not found.');$qty=max(1,(int)($p['quantity']??1));$this->db->query("INSERT INTO orders_services_assigned(id_order,id_service,quantity,unit_price,description,subtotal,id_owner,is_variable) VALUES(:order,:service,:qty,:price,:description,:subtotal,:owner,'NO')");$this->bind(['order'=>$orderId,'service'=>(int)$s->id,'qty'=>$qty,'price'=>(float)$s->price,'description'=>$s->description,'subtotal'=>$qty*(float)$s->price,'owner'=>$this->ownerId]);$this->db->execute();}return $this->result(strtolower(str_replace('CREATE_','',$a)),$orderId,'Borrador creado para revisión','/panel/planner-hub/management/orders/orders/edit?id='.$orderId);}
        if($a==='ADD_NOTE'){$o=$this->order((int)$p['order_id']);$this->db->query("UPDATE orders SET notes=CONCAT_WS('\n',NULLIF(notes,''),:note) WHERE id=:id AND id_owner=:owner");$this->bind(['note'=>'[Mochi '.date('Y-m-d H:i').'] '.$p['note'],'id'=>(int)$o->id,'owner'=>$this->ownerId]);$this->db->execute();return $this->result('order_note',(int)$o->id,'Nota agregada','/panel/planner-hub/management/orders/orders/edit?id='.$o->id);}
        if($a==='CREATE_FOLLOW_UP'){$this->customer((int)$p['customer_id']);$this->db->query("INSERT INTO crm_followups(id_owner,id_customer,id_request,id_order,due_at,subject,notes,created_by) VALUES(:owner,:customer,:request,:order,:due,:subject,:notes,:actor)");$this->bind(['owner'=>$this->ownerId,'customer'=>(int)$p['customer_id'],'request'=>!empty($p['request_id'])?(int)$p['request_id']:null,'order'=>!empty($p['order_id'])?(int)$p['order_id']:null,'due'=>$p['due_at'],'subject'=>$p['subject'],'notes'=>$p['note']??null,'actor'=>$actor]);$this->db->execute();$id=(int)$this->db->lastId();return $this->result('follow_up',$id,$p['subject'],'/panel/planner-hub/management/crm');}
        if($a==='ASSOCIATE_REQUEST_CUSTOMER'){$this->customer((int)$p['customer_id']);$this->db->query("UPDATE event_requests SET id_user=:customer WHERE id=:request AND id_owner=:owner");$this->bind(['customer'=>(int)$p['customer_id'],'request'=>(int)$p['request_id'],'owner'=>$this->ownerId]);$this->db->execute();if(!$this->db->rowCount())throw new \RuntimeException('Request not found.');return $this->result('event_request',(int)$p['request_id'],'Solicitud asociada','/panel/planner-hub/management/requests');}
        if($a==='ASSOCIATE_CUSTOMER_ORDER'){$this->customer((int)$p['customer_id']);$o=$this->order((int)$p['order_id']);$this->db->query("UPDATE orders SET id_client=:customer WHERE id=:order AND id_owner=:owner");$this->bind(['customer'=>(int)$p['customer_id'],'order'=>(int)$o->id,'owner'=>$this->ownerId]);$this->db->execute();return $this->result('order',(int)$o->id,'Cliente asociado','/panel/planner-hub/management/orders/orders/edit?id='.$o->id);}
        if($a==='SEND_CUSTOMER_EMAIL'){$c=$this->customer((int)$p['customer_id']);$sent=EmailServiceFactory::sendWithOwnerProvider($this->ownerId,(string)$c->email,(string)$p['subject'],nl2br(htmlspecialchars((string)$p['body'],ENT_QUOTES,'UTF-8')),true);if(empty($sent['success']))throw new \RuntimeException('Email failed.');return $this->result('customer_email',(int)$c->id,'Email enviado a '.$c->email,'/panel/planner-hub/management/users/edit?id='.$c->id);}
        if($a==='SEND_PUSH_NOTIFICATION'){$c=$this->customer((int)$p['customer_id']);if(empty($c->expo_token))throw new \RuntimeException('Customer has no push token.');NotificationService::sendExpoNotification((string)$c->expo_token,(string)$p['subject'],(string)$p['body'],['source'=>'mochi']);(new NotificationsRepository())->add(['id_user'=>(int)$c->id,'mensaje'=>(string)$p['body'],'link'=>'/panel/home','leido'=>0]);return $this->result('push_notification',(int)$c->id,'Push enviado','/panel/planner-hub/management/users/edit?id='.$c->id);}
        throw new \RuntimeException('Unsupported action.');
    }
    private function summary(string $a,array $p): string {$visible=array_filter($p,fn($key)=>!in_array($key,['customer_id','service_id'],true),ARRAY_FILTER_USE_KEY);return str_replace('_',' ',ucwords(strtolower($a),'_')).' · '.implode(' · ',array_map(fn($k,$v)=>$this->fieldLabel((string)$k).': '.(is_scalar($v)?$v:'información adjunta'),array_keys($visible),$visible));}
    private function result(string $type,int $id,string $details,string $url): array {return ['entity_type'=>$type,'entity_id'=>(string)$id,'details'=>$details,'url'=>$url,'reply'=>ucfirst(str_replace('_',' ',$type)).' #'.$id.' completado — '.$details.'.'];}
    private function customer(int $id): object {$this->db->query("SELECT id,name,lastname,email,phone,expo_token FROM users WHERE id=:id AND id_owner=:owner AND level=5 AND is_active=1");$this->bind(['id'=>$id,'owner'=>$this->ownerId]);$r=$this->db->fetchOne();if(!$r)throw new \RuntimeException('Customer not found.');return $r;}
    private function order(int $id): object {$this->db->query("SELECT id,id_client FROM orders WHERE id=:id AND id_owner=:owner AND COALESCE(is_archived,0)=0");$this->bind(['id'=>$id,'owner'=>$this->ownerId]);$r=$this->db->fetchOne();if(!$r)throw new \RuntimeException('Order not found.');return $r;}
    private function assertAdmin(int $level): void {if($level!==1)throw new \RuntimeException('Only Level 1 can confirm Mochi write actions.');}
    private function audit(?int $draft,int $user,string $action,string $entity,?string $entityId,array $fields,string $status,?string $error=null): void {try{$this->db->query("INSERT INTO mochi_action_audit(id_owner,site_key,id_user,id_action_draft,action_key,entity_type,entity_id,action_source,fields_json,status,error_code) VALUES(:owner,:site,:user,:draft,:action,:entity,:entity_id,'MOCHI',:fields,:status,:error)");$this->bind(['owner'=>$this->ownerId,'site'=>$this->siteKey,'user'=>$user,'draft'=>$draft,'action'=>$action,'entity'=>$entity,'entity_id'=>$entityId,'fields'=>json_encode($fields,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES),'status'=>$status,'error'=>$error]);$this->db->execute();}catch(\Throwable $e){error_log('[Mochi audit] '.$e->getMessage());}}
    private function bind(array $values): void {foreach($values as $k=>$v)$this->db->bind(':'.$k,$v);}
}
