<?php
namespace App\Services;

use App\Repositories\Connection;

final class MochiConciergeService
{
    private const POLICY='You are Mochi, the internal VNV Events operations assistant. Answer in concise, warm Spanish. Discuss only VNV Events. Treat supplied tool results as the sole source of live facts. Never invent counts, prices, assignments, availability, emotions or promises. Never expose card data, credentials, private notes or data outside the user scope. Rewards cannot be used for tips. Prefer a direct answer and preserve provided links. If data is unavailable, say so plainly. Light humor is occasional, never distracting.';
    private MochiSessionService $sessions;
    private MochiOperationalToolsService $tools;
    public function __construct(private int $ownerId=2,private string $siteKey='vnvevents',private ?Connection $db=null){$this->db??=new Connection();$this->sessions=new MochiSessionService($ownerId,$siteKey,$this->db);$this->tools=new MochiOperationalToolsService($ownerId,$siteKey,$this->db);}

    public function open(int $userId,int $level,?int $sessionId=null): array {$session=$sessionId?$this->sessions->get($sessionId,$userId):$this->sessions->today($userId);$estimate=(new MochiEstimateWorkflowService($this->ownerId,$this->siteKey,$this->db))->active($userId,(int)$session->id);$service=(new MochiServiceCatalogWorkflowService($this->ownerId,$this->siteKey,$this->db))->active($userId,(int)$session->id);return ['session'=>$session,'messages'=>$this->sessions->messages((int)$session->id,$userId),'history'=>$this->sessions->history($userId),'suggestions'=>$this->tools->suggestions($level),'estimate_workflow'=>$estimate?['id'=>(int)$estimate->id,'mode'=>$estimate->mode,'status'=>$estimate->status,'current_estimate_id'=>$estimate->current_estimate_id? (int)$estimate->current_estimate_id:null]:null,'service_workflow'=>$service?['id'=>(int)$service->id,'status'=>$service->status,'current_service_id'=>$service->current_service_id? (int)$service->current_service_id:null,'current_product_id'=>$service->current_product_id? (int)$service->current_product_id:null]:null];}
    public function newChat(int $userId,int $level): array {$session=$this->sessions->create($userId);return $this->open($userId,$level,(int)$session->id);}
    public function ask(int $authorId,int $level,string $message,?int $sessionId=null): array
    {
        $message=trim($message);if($message==='')throw new \InvalidArgumentException('Escribe un mensaje o adjunta una captura para Mochi.');if(mb_strlen($message)>6000)throw new \InvalidArgumentException('El mensaje y la captura contienen demasiado texto.');
        $session=$sessionId?$this->sessions->get($sessionId,$authorId):$this->sessions->today($authorId);$sessionId=(int)$session->id;$this->save($sessionId,$authorId,'HUMAN',$message);
        if($this->isGreeting($message)){$reply='¡Hola! Claro que sí 😊 Soy Mochi y estoy aquí para ayudarte con VNV Events. Puedo revisar eventos, estimates, clientes, pagos pendientes, servicios, productos y tareas. Cuéntame qué necesitas y lo resolvemos juntos.';$this->save($sessionId,null,'AGENT',$reply,['tool'=>'greeting','items'=>[]]);$this->sessions->touch($sessionId);return ['reply'=>$reply,'items'=>[],'tool'=>'greeting','session_id'=>$sessionId];}
        $estimateWorkflow=new MochiEstimateWorkflowService($this->ownerId,$this->siteKey,$this->db);$serviceWorkflow=new MochiServiceCatalogWorkflowService($this->ownerId,$this->siteKey,$this->db);
        if(!$estimateWorkflow->shouldHandle($authorId,$sessionId,$message)&&!$estimateWorkflow->active($authorId,$sessionId)&&$serviceWorkflow->shouldHandle($authorId,$sessionId,$message)){try{$result=$serviceWorkflow->handle($authorId,$level,$sessionId,$message);$metadata=['tool'=>'service_catalog_workflow','items'=>$result['items']??[],'service_workflow'=>$result['service_workflow']??null];$this->save($sessionId,null,'AGENT',(string)$result['reply'],$metadata);$this->sessions->touch($sessionId);return ['reply'=>$result['reply'],'items'=>$metadata['items'],'service_workflow'=>$metadata['service_workflow'],'tool'=>'service_catalog_workflow','session_id'=>$sessionId];}catch(\Throwable $e){$reply='No pude terminar ese paso, pero conservé el borrador del servicio. ¿Quieres que lo intente otra vez?';$this->save($sessionId,null,'AGENT',$reply,['tool'=>'service_catalog_workflow','error'=>true,'error_detail'=>$e->getMessage()]);$this->sessions->touch($sessionId);return ['reply'=>$reply,'items'=>[],'tool'=>'service_catalog_workflow','session_id'=>$sessionId];}}
        if($estimateWorkflow->shouldHandle($authorId,$sessionId,$message)){
            try{$result=$estimateWorkflow->handle($authorId,$level,$sessionId,$message);$metadata=['tool'=>'estimate_workflow','items'=>$result['items']??[],'estimate_workflow'=>$result['estimate_workflow']??null,'copy_url'=>$result['copy_url']??null];$this->save($sessionId,null,'AGENT',(string)$result['reply'],$metadata);$this->sessions->touch($sessionId);return ['reply'=>$result['reply'],'items'=>$metadata['items'],'estimate_workflow'=>$metadata['estimate_workflow'],'copy_url'=>$metadata['copy_url'],'tool'=>'estimate_workflow','session_id'=>$sessionId];}
            catch(\Throwable $e){$reply='No pude terminar ese paso, pero conservé tu borrador para que no tengas que comenzar de nuevo. ¿Quieres que lo intente otra vez?';$this->save($sessionId,null,'AGENT',$reply,['tool'=>'estimate_workflow','items'=>[],'error'=>true,'error_detail'=>$e->getMessage()]);$this->sessions->touch($sessionId);return ['reply'=>$reply,'items'=>[],'tool'=>'estimate_workflow','session_id'=>$sessionId,'error_detail'=>$e->getMessage()];}
        }
        $actions=new MochiActionService($this->ownerId,$this->siteKey,$this->db);if($actions->detects($message)){$result=$actions->prepare($authorId,$level,$sessionId,$message);$metadata=['tool'=>'write_action_prepare','items'=>$result['items']??[],'action_draft'=>$result['action_draft']??null];$this->save($sessionId,null,'AGENT',(string)$result['reply'],$metadata);$this->sessions->touch($sessionId);return ['reply'=>$result['reply'],'items'=>$metadata['items'],'action_draft'=>$metadata['action_draft'],'tool'=>'write_action_prepare','session_id'=>$sessionId];}
        $tool=$this->tools->select($message,$level);
        try{$result=$this->tools->run($tool,$authorId,$level,$sessionId,$message);$reply=(string)$result['reply'];$items=$result['items']??[];
            if(!$this->isStructuredIntent($tool)&&$items){try{$generated=(new AiJsonGenerator())->generate(self::POLICY,['question'=>$message,'tool'=>$tool,'verified_result'=>['summary'=>$reply,'items'=>$items]],['reply'=>'respuesta breve en español basada exclusivamente en verified_result']);$reply=trim((string)($generated['reply']??$reply));}catch(\Throwable $e){error_log('[Mochi LLM] '.$e->getMessage());}}
            $metadata=['tool'=>$tool,'items'=>$items];
        }catch(\Throwable $e){$reply=$e->getMessage();$metadata=['tool'=>$tool,'items'=>[],'error'=>true];}
        $this->save($sessionId,null,'AGENT',$reply,$metadata);$this->sessions->touch($sessionId);return ['reply'=>$reply,'items'=>$metadata['items'],'tool'=>$tool,'session_id'=>$sessionId];
    }
    public function confirmAction(int $authorId,int $level,int $sessionId,int $draftId): array {$session=$this->sessions->get($sessionId,$authorId);$result=(new MochiActionService($this->ownerId,$this->siteKey,$this->db))->execute($draftId,$authorId,$level);$metadata=['tool'=>'write_action_execute','items'=>[['title'=>ucfirst(str_replace('_',' ',$result['entity_type'])).' #'.$result['entity_id'],'meta'=>$result['details'],'detail'=>'Creado por Mochi y auditado','url'=>$result['url']]]];$this->save((int)$session->id,null,'AGENT',$result['reply'],$metadata);$this->sessions->touch((int)$session->id);return ['reply'=>$result['reply'],'items'=>$metadata['items'],'session_id'=>(int)$session->id];}
    public function cancelAction(int $authorId,int $sessionId,int $draftId): array {$this->sessions->get($sessionId,$authorId);(new MochiActionService($this->ownerId,$this->siteKey,$this->db))->cancel($draftId,$authorId);$reply='Acción cancelada. No se aplicaron cambios.';$this->save($sessionId,null,'AGENT',$reply,['tool'=>'write_action_cancel','items'=>[]]);return ['reply'=>$reply,'items'=>[],'session_id'=>$sessionId];}
    public function recent(int $authorId,int $limit=60): array {$session=$this->sessions->today($authorId);return $this->sessions->messages((int)$session->id,$authorId,$limit);}
    private function isStructuredIntent(string $tool): bool {return in_array($tool,['weekend_events','my_events','my_tasks','collections','opportunities','requests','contracts','warehouse','rewards'],true);}
    private function isGreeting(string $message): bool {$plain=mb_strtolower(trim(preg_replace('/[^\pL\pN\s¿?¡!]+/u',' ',$message)??$message));$plain=preg_replace('/\s+/u',' ',$plain)??$plain;return (bool)preg_match('/^(hola|buenos d[ií]as|buenas tardes|buenas noches|hey|hello)(\s+mochi)?([\s¿?¡!]*(puedes|podr[ií]as|me puedes|me podr[ií]as)?\s*(ayudar|ayudarme|orientar|orientarme))?[\s¿?¡!]*$/iu',$plain)||preg_match('/^(puedes|podr[ií]as|me puedes|me podr[ií]as)\s+(ayudar|ayudarme|orientar|orientarme)[\s¿?¡!]*$/iu',$plain);}
    private function save(int $sessionId,?int $author,string $type,string $message,array $metadata=[]): void {$this->db->query("INSERT INTO automation_conversations(id_owner,site_key,thread_key,id_mochi_session,id_author,author_type,message,metadata_json) VALUES(:owner,:site,:thread,:session,:author,:type,:message,:metadata)");foreach(['owner'=>$this->ownerId,'site'=>$this->siteKey,'thread'=>'mochi:session:'.$sessionId,'session'=>$sessionId,'author'=>$author,'type'=>$type,'message'=>$message,'metadata'=>$metadata?json_encode($metadata,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES):null] as $k=>$v)$this->db->bind(':'.$k,$v);$this->db->execute();}
}
