<?php
namespace App\Services;

use App\Repositories\Connection;

/** Read-only, role-scoped operational queries used by Mochi. */
final class MochiOperationalToolsService
{
    private const ADMIN_TOOLS=['weekend_events','collections','opportunities','requests','contracts','catalog','warehouse','rewards','customer_orders','website'];
    private const TEAM_TOOLS=['my_events','my_tasks','catalog','website'];
    private const CLIENT_TOOLS=['my_events','catalog','website','rewards'];
    public function __construct(private int $ownerId,private string $siteKey='vnvevents',private ?Connection $db=null){$this->db??=new Connection();}

    public function select(string $message,int $level): string
    {
        $m=mb_strtolower($message);
        if(preg_match('/paella|lasagna|pasticho|gourmet|producto|paquete|caviar|comida|personas|add.?on|precio|cu[aá]nto cuesta|nochebuena|navidad/iu',$m))return 'catalog';
        if(preg_match('/punto|reward/iu',$m))return 'rewards';
        if(preg_match('/contenedor|warehouse|inventario|almac[eé]n/iu',$m))return 'warehouse';
        if(preg_match('/contrato|firma/iu',$m))return 'contracts';
        if(preg_match('/estimado|lead|oportunidad|seguimiento/iu',$m))return 'opportunities';
        if(preg_match('/solicitud|request|unread|sin leer/iu',$m))return 'requests';
        if(preg_match('/saldo|debe|cobro|pago pendiente|outstanding/iu',$m))return 'collections';
        if(preg_match('/tarea/iu',$m))return $level===4?'my_tasks':'weekend_events';
        if(preg_match('/evento|agenda|calendario|manager|gerente|staff|equipo/iu',$m))return $level===1?'weekend_events':'my_events';
        if(preg_match('/servicio|p[aá]gina|website|sitio/iu',$m))return 'website';
        return 'website';
    }

    public function run(string $tool,int $userId,int $level,int $sessionId,string $message=''): array
    {
        $allowed=$level===1?self::ADMIN_TOOLS:($level===4?self::TEAM_TOOLS:($level===5?self::CLIENT_TOOLS:[]));$start=microtime(true);
        if(!in_array($tool,$allowed,true)){$this->log($userId,$sessionId,$tool,'DENIED',$start,0,'ROLE_SCOPE');throw new \RuntimeException('Esa información no está disponible para tu nivel de acceso.');}
        try{$result=match($tool){'weekend_events'=>$this->weekendEvents(),'my_events'=>$this->myEvents($userId,$level),'my_tasks'=>$this->myTasks($userId),'collections'=>$this->collections(),'opportunities'=>$this->opportunities(),'requests'=>$this->requests(),'contracts'=>$this->contracts(),'catalog'=>$this->catalog($message),'warehouse'=>$this->warehouse(),'rewards'=>$this->rewards($userId,$level,$message),'customer_orders'=>$this->myEvents($userId,$level),'website'=>$this->website($message)};$this->log($userId,$sessionId,$tool,'SUCCESS',$start,count($result['items']??[]));return ['tool'=>$tool]+$result;}
        catch(\Throwable $e){$this->log($userId,$sessionId,$tool,'FAILED',$start,0,'QUERY_FAILED');error_log('[Mochi tool '.$tool.'] '.$e->getMessage());throw new \RuntimeException('No pude recuperar esos datos ahora mismo. Intenta nuevamente.');}
    }

    public function suggestions(int $level): array {$this->db->query("SELECT title,prompt,icon FROM mochi_suggested_prompts WHERE id_owner=:owner AND site_key=:site AND user_level=:level AND status='ACTIVE' ORDER BY sort_order,id LIMIT 4");$this->bind(['owner'=>$this->ownerId,'site'=>$this->siteKey,'level'=>$level]);return $this->db->fetchAll();}

    private function weekendEvents(): array
    {
        [$start,$end]=$this->weekend();$sql="SELECT o.id,o.event_date,o.start_time,o.address,o.status_workflow,o.payment_status,o.main_manager_id,CONCAT_WS(' ',c.name,c.lastname) customer,CONCAT_WS(' ',m.name,m.lastname) manager,COALESCE((SELECT SUM(osa.subtotal) FROM orders_services_assigned osa WHERE osa.id_order=o.id),0) total,COUNT(DISTINCT ott.id_user) team_count FROM orders o LEFT JOIN users c ON c.id=o.id_client LEFT JOIN users m ON m.id=o.main_manager_id LEFT JOIN orders_team_tasks ott ON ott.id_order=o.id WHERE o.id_owner=:owner AND COALESCE(o.is_archived,0)=0 AND o.event_date BETWEEN :start AND :end GROUP BY o.id ORDER BY o.event_date,o.start_time";$this->db->query($sql);$this->bind(['owner'=>$this->ownerId,'start'=>$start,'end'=>$end]);$items=$this->rows($this->db->fetchAll(),fn($r)=>['title'=>'Evento #'.$r->id.' · '.($r->customer?:'Cliente sin nombre'),'meta'=>$r->event_date.' '.substr((string)$r->start_time,0,5).' · '.($r->address?:'Ubicación pendiente'),'detail'=>'Valor: $'.number_format((float)$r->total,2).' · Gerente: '.($r->manager?:'NO ASIGNADO').' · Equipo: '.(int)$r->team_count,'flag'=>!$r->main_manager_id?'Gerente no asignado':((int)$r->team_count===0?'Equipo no asignado':''),'url'=>'/panel/planner-hub/management/orders/orders/edit?id='.(int)$r->id]);return ['reply'=>count($items).' evento(s) entre '.$start.' y '.$end.'.','items'=>$items];
    }
    private function myEvents(int $userId,int $level): array {$scope=$level===5?'o.id_client=:user':'(o.main_manager_id=:user OR EXISTS(SELECT 1 FROM orders_team_tasks t WHERE t.id_order=o.id AND t.id_user=:user))';$this->db->query("SELECT DISTINCT o.id,o.event_date,o.start_time,o.address,o.status_workflow FROM orders o WHERE o.id_owner=:owner AND COALESCE(o.is_archived,0)=0 AND o.event_date>=CURDATE() AND {$scope} ORDER BY o.event_date,o.start_time LIMIT 20");$this->bind(['owner'=>$this->ownerId,'user'=>$userId]);$items=$this->rows($this->db->fetchAll(),fn($r)=>['title'=>'Evento #'.$r->id,'meta'=>$r->event_date.' '.substr((string)$r->start_time,0,5),'detail'=>(string)$r->address,'url'=>'/panel/event-execution?order_id='.(int)$r->id]);return ['reply'=>count($items).' evento(s) próximo(s) dentro de tu acceso.','items'=>$items];}
    private function myTasks(int $userId): array {$this->db->query("SELECT t.id,t.task_description,t.is_done,o.id order_id,o.event_date FROM orders_team_tasks t JOIN orders o ON o.id=t.id_order WHERE o.id_owner=:owner AND t.id_user=:user AND COALESCE(t.is_done,0)=0 AND o.event_date>=CURDATE() ORDER BY o.event_date LIMIT 30");$this->bind(['owner'=>$this->ownerId,'user'=>$userId]);$items=$this->rows($this->db->fetchAll(),fn($r)=>['title'=>(string)$r->task_description,'meta'=>'Evento #'.$r->order_id.' · '.$r->event_date,'detail'=>'Pendiente','url'=>'/panel/event-execution?order_id='.(int)$r->order_id]);return ['reply'=>count($items).' tarea(s) pendiente(s).','items'=>$items];}
    private function collections(): array {$this->db->query("SELECT q.*,GREATEST(q.subtotal+(q.subtotal*q.tax_percentage/100)-CASE WHEN q.discount_type='percent' THEN q.subtotal*q.discount_value/100 ELSE q.discount_value END,0) total FROM (SELECT o.id,o.event_date,o.payment_status,o.tax_percentage,COALESCE(o.discount_type,'fixed') discount_type,COALESCE(o.discount_value,0) discount_value,CONCAT_WS(' ',u.name,u.lastname) customer,COALESCE((SELECT SUM(s.subtotal) FROM orders_services_assigned s WHERE s.id_order=o.id),0) subtotal,COALESCE((SELECT SUM(p.amount-COALESCE(p.refunded_amount,0)) FROM orders_payments p WHERE p.id_order=o.id AND COALESCE(p.is_refunded,0)=0),0) paid FROM orders o LEFT JOIN users u ON u.id=o.id_client WHERE o.id_owner=:owner AND COALESCE(o.is_archived,0)=0) q HAVING total-paid>0 ORDER BY total-paid DESC LIMIT 10");$this->db->bind(':owner',$this->ownerId);$items=$this->rows($this->db->fetchAll(),fn($r)=>['title'=>($r->customer?:'Cliente').' · Evento #'.$r->id,'meta'=>'Saldo: $'.number_format((float)$r->total-(float)$r->paid,2).' · Total: $'.number_format((float)$r->total,2),'detail'=>'Pagado: $'.number_format((float)$r->paid,2).' · Evento: '.$r->event_date,'url'=>'/panel/planner-hub/management/orders/orders/edit?id='.(int)$r->id]);return ['reply'=>'Los '.count($items).' saldos pendientes más altos, ordenados por monto.','items'=>$items];}
    private function opportunities(): array {$this->db->query("SELECT o.id,o.event_date,o.created_at,CONCAT_WS(' ',u.name,u.lastname) customer,COALESCE((SELECT SUM(s.subtotal) FROM orders_services_assigned s WHERE s.id_order=o.id),0) value FROM orders o LEFT JOIN users u ON u.id=o.id_client WHERE o.id_owner=:owner AND COALESCE(o.is_archived,0)=0 AND o.status_workflow='INVOICE_DRAFT' ORDER BY value DESC,o.created_at LIMIT 10");$this->db->bind(':owner',$this->ownerId);$items=$this->rows($this->db->fetchAll(),fn($r)=>['title'=>'Estimado #'.$r->id.' · '.($r->customer?:'Cliente'),'meta'=>'$'.number_format((float)$r->value,2).' · Evento: '.$r->event_date,'detail'=>'Prioridad factual: estimado abierto; creado '.$r->created_at,'url'=>'/panel/planner-hub/management/orders/orders/edit?id='.(int)$r->id]);return ['reply'=>count($items).' estimado(s) abierto(s), ordenados por valor.','items'=>$items];}
    private function requests(): array {$this->db->query("SELECT id,full_name,event_date,guest_count,status,created_at FROM event_requests WHERE id_owner=:owner AND COALESCE(is_archived,0)=0 AND status NOT IN ('CLOSED','CONVERTED') ORDER BY created_at LIMIT 10");$this->db->bind(':owner',$this->ownerId);$items=$this->rows($this->db->fetchAll(),fn($r)=>['title'=>'Solicitud #'.$r->id.' · '.$r->full_name,'meta'=>'Evento: '.$r->event_date.' · Invitados: '.(int)$r->guest_count,'detail'=>'Estado: '.$r->status.' · Recibida: '.$r->created_at,'url'=>'/panel/planner-hub/management/requests']);return ['reply'=>count($items).' solicitud(es) abiertas.','items'=>$items];}
    private function contracts(): array {$this->db->query("SELECT o.id,o.event_date,CONCAT_WS(' ',u.name,u.lastname) customer,CASE WHEN EXISTS(SELECT 1 FROM orders_acceptance_contracts ac WHERE ac.id_order=o.id) THEN 1 ELSE 0 END signed FROM orders o LEFT JOIN users u ON u.id=o.id_client WHERE o.id_owner=:owner AND COALESCE(o.is_archived,0)=0 AND o.event_date>=CURDATE() HAVING signed=0 ORDER BY o.event_date LIMIT 15");$this->db->bind(':owner',$this->ownerId);$items=$this->rows($this->db->fetchAll(),fn($r)=>['title'=>'Evento #'.$r->id.' · '.($r->customer?:'Cliente'),'meta'=>'Evento: '.$r->event_date,'detail'=>'Contrato sin firma registrada','url'=>'/panel/planner-hub/management/orders/orders/edit?id='.(int)$r->id]);return ['reply'=>count($items).' evento(s) próximo(s) sin firma registrada.','items'=>$items];}
    private function catalog(string $message): array {$terms=array_values(array_filter(preg_split('/[^\pL\pN]+/u',mb_strtolower($message),-1,PREG_SPLIT_NO_EMPTY),fn($x)=>mb_strlen($x)>3&&!in_array($x,['cuanto','cuánto','precio','personas','puedo','ofrecer','producto','productos','paquete','paquetes','tiene','para','staff'],true)));$where='';$params=['owner'=>$this->ownerId,'site'=>$this->siteKey];if($terms){$search="LOWER(CONCAT_WS(' ',CONVERT(p.name USING utf8mb4),CONVERT(p.short_description USING utf8mb4),CONVERT(p.description USING utf8mb4))) COLLATE utf8mb4_unicode_ci";$where=' AND ('.implode(' OR ',array_map(fn($i)=>"{$search} LIKE CONVERT(:q{$i} USING utf8mb4) COLLATE utf8mb4_unicode_ci",array_keys(array_slice($terms,0,4)))).')';foreach(array_slice($terms,0,4) as $i=>$term)$params['q'.$i]='%'.$term.'%';}$this->db->query("SELECT p.id,p.name,p.slug,p.short_description,p.price,p.promo_price,p.product_type,p.fulfillment_type,p.lead_hours,p.min_purchase_qty,MIN(v.price) min_price,MAX(v.price) max_price,GROUP_CONCAT(CONCAT(CONVERT(v.name USING utf8mb4),': $',FORMAT(v.price,2)) ORDER BY v.sort_order SEPARATOR ' | ') variations FROM store_products p LEFT JOIN store_product_variations v ON v.id_product=p.id AND v.status='ACTIVE' WHERE p.id_owner=:owner AND p.site_key=:site AND p.status='ACTIVE' AND p.is_public=1 {$where} GROUP BY p.id ORDER BY p.is_featured DESC,p.name LIMIT 12");$this->bind($params);$items=$this->rows($this->db->fetchAll(),function($r){$price=$r->product_type==='VARIABLE'?'$'.number_format((float)$r->min_price,2).' - $'.number_format((float)$r->max_price,2):'$'.number_format((float)($r->promo_price?:$r->price),2);return ['title'=>$r->name,'meta'=>$price.' · '.str_replace('_',' ',(string)$r->fulfillment_type),'detail'=>trim(strip_tags((string)$r->short_description)).($r->variations?' · '.$r->variations:''),'url'=>'/vnv-gourmet-express/product/'.$r->slug];});return ['reply'=>count($items).' producto(s) activo(s), con precios consultados ahora mismo.','items'=>$items];}
    private function warehouse(): array {$this->db->query("SELECT c.id,c.name,COUNT(i.id) item_types,COALESCE(SUM(i.quantity),0) units FROM storage_containers c LEFT JOIN storage_items i ON i.id_container=c.id WHERE c.id_owner=:owner GROUP BY c.id ORDER BY c.name LIMIT 30");$this->db->bind(':owner',$this->ownerId);$items=$this->rows($this->db->fetchAll(),fn($r)=>['title'=>$r->name,'meta'=>(int)$r->units.' unidades · '.(int)$r->item_types.' tipos','detail'=>'Contenedor de almacén','url'=>'/panel/planner-hub/storage']);return ['reply'=>count($items).' contenedor(es) registrados. El esquema actual no vincula contenedores directamente con eventos.','items'=>$items];}
    private function rewards(int $userId,int $level,string $message): array {if($level===1){$ids=$this->customerIds($message);if(count($ids)!==1)return ['reply'=>count($ids)>1?'Encontré varios clientes; escribe el nombre completo.':'Indica el nombre del cliente para consultar sus puntos.','items'=>[]];$userId=$ids[0];}$this->db->query("SELECT COALESCE(SUM(CASE WHEN status='AVAILABLE' THEN points ELSE 0 END),0) points,COALESCE(SUM(CASE WHEN status='AVAILABLE' THEN monetary_value ELSE 0 END),0) value FROM loyalty_transactions WHERE id_owner=:owner AND site_key=:site AND id_user=:user");$this->bind(['owner'=>$this->ownerId,'site'=>$this->siteKey,'user'=>$userId]);$r=$this->db->fetchOne();return ['reply'=>'Puntos disponibles: '.number_format((float)$r->points,2).' · Valor registrado: $'.number_format((float)$r->value,2).'. Los rewards no pueden usarse para tips.','items'=>[]];}
    private function website(string $message): array {$terms=array_values(array_filter(preg_split('/[^\pL\pN]+/u',mb_strtolower($message),-1,PREG_SPLIT_NO_EMPTY),fn($x)=>mb_strlen($x)>3&&!in_array($x,['servicio','servicios','ofrece','pagina','página','vnv','events'],true)));$where='';$params=['owner'=>$this->ownerId,'site'=>$this->siteKey];if($terms){$where=' AND ('.implode(' OR ',array_map(fn($i)=>"LOWER(CONCAT_WS(' ',c.title,c.excerpt,c.body_html)) LIKE :q{$i}",array_keys(array_slice($terms,0,3)))).')';foreach(array_slice($terms,0,3) as $i=>$term)$params['q'.$i]='%'.$term.'%';}$this->db->query("SELECT c.title,c.excerpt,r.route FROM cms_contents c JOIN cms_routes r ON r.id_content=c.id AND r.status='ACTIVE' WHERE c.id_owner=:owner AND c.site_key=:site AND c.status='PUBLISHED' {$where} ORDER BY c.updated_at DESC LIMIT 10");$this->bind($params);$items=$this->rows($this->db->fetchAll(),fn($r)=>['title'=>$r->title,'meta'=>'Servicio o contenido público','detail'=>trim(strip_tags((string)$r->excerpt)),'url'=>'/'.ltrim((string)$r->route,'/')]);return ['reply'=>$items?count($items).' página(s) relevante(s) del CMS.':'No encontré una página publicada coincidente. Puedes preguntarme por un servicio o producto concreto.','items'=>$items];}

    private function weekend(): array {$now=new \DateTimeImmutable('now',new \DateTimeZone('America/New_York'));$friday=$now->modify('friday this week');if((int)$now->format('N')>5)$friday=$now->modify('friday last week');return [$friday->format('Y-m-d'),$friday->modify('+2 days')->format('Y-m-d')];}
    private function customerIds(string $message): array {$tokens=array_slice(array_values(array_filter(preg_split('/[^\pL\pN@._-]+/u',mb_strtolower($message),-1,PREG_SPLIT_NO_EMPTY),fn($x)=>mb_strlen($x)>3&&!in_array($x,['puntos','cliente','cuantos','cuántos','tiene','disponible','mochi'],true))),0,4);if(!$tokens)return [];$where=[];foreach($tokens as $i=>$t)$where[]="LOWER(CONCAT_WS(' ',name,lastname)) LIKE :n{$i}";$this->db->query("SELECT id FROM users WHERE id_owner=:owner AND level=5 AND (".implode(' OR ',$where).") LIMIT 5");$this->db->bind(':owner',$this->ownerId);foreach($tokens as $i=>$t)$this->db->bind(':n'.$i,'%'.$t.'%');return array_map(fn($r)=>(int)$r->id,$this->db->fetchAll());}
    private function rows(array $rows,callable $map): array {return array_map($map,$rows);}
    private function bind(array $values): void {foreach($values as $key=>$value)$this->db->bind(':'.$key,$value);}
    private function log(int $user,int $session,string $tool,string $status,float $start,int $count,string $error=null): void {try{$this->db->query("INSERT INTO mochi_tool_logs(id_owner,site_key,id_user,id_session,tool_key,status,duration_ms,result_count,error_code) VALUES(:owner,:site,:user,:session,:tool,:status,:duration,:count,:error)");$this->bind(['owner'=>$this->ownerId,'site'=>$this->siteKey,'user'=>$user,'session'=>$session,'tool'=>$tool,'status'=>$status,'duration'=>(int)((microtime(true)-$start)*1000),'count'=>$count,'error'=>$error]);$this->db->execute();}catch(\Throwable){} }
}
