-- VNV Gourmet To Go real launch catalog. Idempotent and scoped to owner 2 / vnvevents.
SET NAMES utf8mb4;
START TRANSACTION;

INSERT INTO store_categories (id_owner,site_key,name,slug,description,status,created_at,updated_at) VALUES
(2,'vnvevents','Family Meals','family-meals','Prepared family meals for pickup or delivery.','ACTIVE',NOW(),NOW()),
(2,'vnvevents','Party Boxes','party-boxes','Curated appetizer and grazing boxes for gatherings.','ACTIVE',NOW(),NOW()),
(2,'vnvevents','Party Trays','party-trays','Prepared catering trays for celebrations and meetings.','ACTIVE',NOW(),NOW()),
(2,'vnvevents','Desserts & Add-Ons','desserts-add-ons','Desserts and optional additions for Gourmet To Go orders.','ACTIVE',NOW(),NOW()),
(2,'vnvevents','Seasonal & Holiday Packages','seasonal-holiday-packages','Limited seasonal and holiday menus.','ACTIVE',NOW(),NOW())
ON DUPLICATE KEY UPDATE name=VALUES(name),description=VALUES(description),status='ACTIVE',updated_at=NOW();

-- Products are matched by the existing unique owner + slug key. Existing unrelated catalog rows are untouched.
INSERT INTO store_products (id_owner,site_key,name,slug,sku,brand_name,short_description,description,product_type,purchase_mode,allow_immediate_payment,allow_recurring_purchase,fulfillment_type,price,currency_code,main_image,stock_quantity,min_purchase_qty,is_featured,is_public,status,created_at,updated_at) VALUES
(2,'vnvevents','Homemade Lasagna / Pasticho','homemade-lasagna-pasticho','VNV-GTG-LAS','VNV Gourmet To Go','Traditional beef, chicken or vegetarian.','<p>Traditional beef, chicken or vegetarian lasagna/pasticho, prepared to order.</p>','VARIABLE','DIRECT',1,1,'DELIVERY',0,'USD','/assets/images/vnv-gourmet-hero-small-fast.webp',999,1,1,1,'ACTIVE',NOW(),NOW()),
(2,'vnvevents','Latin Bites Box','latin-bites-box','VNV-GTG-LBB','VNV Gourmet To Go','Tequeños, mini empanadas, croquetas, mini arepitas & signature sauces.','<p>A festive assortment of Latin bites with signature sauces.</p>','VARIABLE','DIRECT',1,1,'DELIVERY',0,'USD','/assets/images/vnv-gourmet-hero-small-fast.webp',999,1,1,1,'ACTIVE',NOW(),NOW()),
(2,'vnvevents','Signature Appetizer Box','signature-appetizer-box','VNV-GTG-SAB','VNV Gourmet To Go','A premium mix for gatherings, showers, meetings & celebrations.','<p>A premium appetizer mix prepared for effortless entertaining.</p>','VARIABLE','DIRECT',1,1,'DELIVERY',0,'USD','/assets/images/vnv-gourmet-hero-small-fast.webp',999,1,1,1,'ACTIVE',NOW(),NOW()),
(2,'vnvevents','Charcuterie To Go','charcuterie-to-go','VNV-GTG-CHAR','VNV Gourmet To Go','Cheeses, cured meats, fruit, nuts, crackers & accompaniments.','<p>A ready-to-serve charcuterie selection with accompaniments.</p>','VARIABLE','DIRECT',1,1,'DELIVERY',0,'USD','/assets/images/vnv-gourmet-hero-small-fast.webp',999,1,1,1,'ACTIVE',NOW(),NOW()),
(2,'vnvevents','Chicken & Chorizo Paella','chicken-chorizo-paella','VNV-GTG-CCP','VNV Gourmet To Go','Chicken, chorizo, saffron rice, vegetables and traditional paella seasoning.','<p>Delivered in a premium disposable catering tray. No equipment return is required.</p>','VARIABLE','DIRECT',1,1,'DELIVERY',0,'USD','/assets/images/vnv-gourmet-hero-small-fast.webp',999,1,1,1,'ACTIVE',NOW(),NOW()),
(2,'vnvevents','Seafood Paella','seafood-paella','VNV-GTG-SP','VNV Gourmet To Go','Seafood paella with shrimp, mussels and seasonal seafood selection.','<p>Delivered in a premium disposable catering tray. No equipment return is required.</p>','VARIABLE','DIRECT',1,1,'DELIVERY',0,'USD','/assets/images/vnv-gourmet-hero-small-fast.webp',999,1,1,1,'ACTIVE',NOW(),NOW()),
(2,'vnvevents','Dessert Box','dessert-box','VNV-GTG-DB','VNV Gourmet To Go','A curated dessert assortment for gatherings.','<p>A shareable selection of VNV desserts.</p>','VARIABLE','DIRECT',1,1,'DELIVERY',0,'USD','/assets/images/vnv-gourmet-hero-small-fast.webp',999,1,0,1,'ACTIVE',NOW(),NOW()),
(2,'vnvevents','Ensaimada Box','ensaimada-box','VNV-GTG-EB','VNV Gourmet To Go','Traditional ensaimadas packed for sharing.','<p>A box of traditional ensaimadas, ready to serve.</p>','VARIABLE','DIRECT',1,1,'DELIVERY',0,'USD','/assets/images/vnv-gourmet-hero-small-fast.webp',999,1,0,1,'ACTIVE',NOW(),NOW()),
(2,'vnvevents','Garlic Bread','garlic-bread','VNV-GTG-GB','VNV Gourmet To Go','Garlic bread add-on.','<p>Optional garlic bread for your Gourmet To Go order.</p>','FIXED','DIRECT',1,1,'DELIVERY',15,'USD','/assets/images/vnv-gourmet-hero-small-fast.webp',999,1,0,1,'ACTIVE',NOW(),NOW()),
(2,'vnvevents','Salad Add-On','salad-add-on','VNV-GTG-SAL','VNV Gourmet To Go','Fresh salad add-on.','<p>Optional fresh salad for your Gourmet To Go order.</p>','FIXED','DIRECT',1,1,'DELIVERY',22,'USD','/assets/images/vnv-gourmet-hero-small-fast.webp',999,1,0,1,'ACTIVE',NOW(),NOW()),
(2,'vnvevents','Extra Dessert Add-On','extra-dessert-add-on','VNV-GTG-EDA','VNV Gourmet To Go','Additional dessert add-on.','<p>Optional additional dessert selection.</p>','FIXED','DIRECT',1,1,'DELIVERY',25,'USD','/assets/images/vnv-gourmet-hero-small-fast.webp',999,1,0,1,'ACTIVE',NOW(),NOW()),
(2,'vnvevents','Thanksgiving Feast','thanksgiving-feast','VNV-GTG-TF','VNV Gourmet To Go','$65 per person with a 15 guest minimum.','<p>Whole herb-roasted turkey, honey-pineapple glazed ham, mashed potatoes with gravy, house stuffing, roasted fall vegetables, cranberry sauce, dinner rolls and mini pumpkin cheesecakes. Includes professional buffet table setup, risers, trays, chafers, design layout, premium disposable place settings and themed styling. Staff, delivery and taxes are additional.</p>','FIXED','DIRECT',1,0,'DELIVERY',65,'USD','/assets/images/vnv-gourmet-hero-small-fast.webp',999,15,1,1,'ACTIVE',NOW(),NOW()),
(2,'vnvevents','Thanksgiving Dinner To Go','thanksgiving-dinner-to-go','VNV-GTG-TDTG','VNV Gourmet To Go','A complete Thanksgiving dinner prepared to go.','<p>A holiday dinner package priced by serving-size tray. Delivery and taxes are additional.</p>','VARIABLE','DIRECT',1,0,'DELIVERY',0,'USD','/assets/images/vnv-gourmet-hero-small-fast.webp',999,1,1,1,'ACTIVE',NOW(),NOW()),
(2,'vnvevents','Venezuelan Christmas Dinner','venezuelan-christmas-dinner','VNV-GTG-VCD','VNV Gourmet To Go','Hallacas, pernil, ensalada de gallina & pan de jamón.','<p>A Venezuelan holiday dinner prepared to order.</p>','VARIABLE','DIRECT',1,0,'DELIVERY',0,'USD','/assets/images/vnv-gourmet-hero-small-fast.webp',999,1,1,1,'ACTIVE',NOW(),NOW()),
(2,'vnvevents','Latin Holiday Dinner','latin-holiday-dinner','VNV-GTG-LHD','VNV Gourmet To Go','Pernil, rice, yuca, sweet plantains & salad.','<p>A Latin holiday dinner prepared to order.</p>','VARIABLE','DIRECT',1,0,'DELIVERY',0,'USD','/assets/images/vnv-gourmet-hero-small-fast.webp',999,1,1,1,'ACTIVE',NOW(),NOW()),
(2,'vnvevents','Extra Hallaca','extra-hallaca','VNV-GTG-EH','VNV Gourmet To Go','Extra hallaca holiday add-on.','<p>Add an extra hallaca to an eligible holiday order.</p>','FIXED','DIRECT',1,0,'DELIVERY',14,'USD','/assets/images/vnv-gourmet-hero-small-fast.webp',999,1,0,1,'ACTIVE',NOW(),NOW()),
(2,'vnvevents','Pan de Jamón','pan-de-jamon','VNV-GTG-PJ','VNV Gourmet To Go','Traditional pan de jamón add-on.','<p>Add a traditional pan de jamón to an eligible holiday order.</p>','FIXED','DIRECT',1,0,'DELIVERY',34,'USD','/assets/images/vnv-gourmet-hero-small-fast.webp',999,1,0,1,'ACTIVE',NOW(),NOW()),
(2,'vnvevents','Pernil by the Pound','pernil-by-the-pound','VNV-GTG-PBP','VNV Gourmet To Go','Pernil sold by the pound.','<p>Add prepared pernil by the pound to an eligible holiday order.</p>','FIXED','DIRECT',1,0,'DELIVERY',18,'USD','/assets/images/vnv-gourmet-hero-small-fast.webp',999,1,0,1,'ACTIVE',NOW(),NOW())
ON DUPLICATE KEY UPDATE site_key='vnvevents',name=VALUES(name),sku=VALUES(sku),brand_name=VALUES(brand_name),short_description=VALUES(short_description),description=VALUES(description),product_type=VALUES(product_type),purchase_mode='DIRECT',allow_immediate_payment=1,allow_recurring_purchase=VALUES(allow_recurring_purchase),fulfillment_type='DELIVERY',price=VALUES(price),currency_code='USD',main_image=COALESCE(NULLIF(main_image,''),VALUES(main_image)),stock_quantity=999,min_purchase_qty=VALUES(min_purchase_qty),is_public=1,status='ACTIVE',updated_at=NOW();

-- Exact variation matrix. Existing matching slugs are updated; missing rows are inserted.
INSERT INTO store_product_variations (id_owner,id_product,name,slug,sku,price,currency_code,stock_quantity,min_purchase_qty,sort_order,status,created_at,updated_at)
SELECT 2,p.id,v.name,v.slug,v.sku,v.price,'USD',999,1,v.sort_order,'ACTIVE',NOW(),NOW() FROM store_products p JOIN (
SELECT 'homemade-lasagna-pasticho' product_slug,'Traditional Beef · Serves 6' name,'traditional-beef-serves-6' slug,'VNV-LAS-B6' sku,89.00 price,10 sort_order UNION ALL SELECT 'homemade-lasagna-pasticho','Traditional Beef · Serves 8','traditional-beef-serves-8','VNV-LAS-B8',119,20 UNION ALL SELECT 'homemade-lasagna-pasticho','Traditional Beef · Serves 12','traditional-beef-serves-12','VNV-LAS-B12',179,30 UNION ALL SELECT 'homemade-lasagna-pasticho','Chicken · Serves 6','chicken-serves-6','VNV-LAS-C6',89,40 UNION ALL SELECT 'homemade-lasagna-pasticho','Chicken · Serves 8','chicken-serves-8','VNV-LAS-C8',119,50 UNION ALL SELECT 'homemade-lasagna-pasticho','Chicken · Serves 12','chicken-serves-12','VNV-LAS-C12',179,60 UNION ALL SELECT 'homemade-lasagna-pasticho','Vegetarian · Serves 6','vegetarian-serves-6','VNV-LAS-V6',89,70 UNION ALL SELECT 'homemade-lasagna-pasticho','Vegetarian · Serves 8','vegetarian-serves-8','VNV-LAS-V8',119,80 UNION ALL SELECT 'homemade-lasagna-pasticho','Vegetarian · Serves 12','vegetarian-serves-12','VNV-LAS-V12',179,90 UNION ALL
SELECT 'latin-bites-box','Serves 6–8','serves-6-8','VNV-LBB-68',109,10 UNION ALL SELECT 'latin-bites-box','Serves 10–12','serves-10-12','VNV-LBB-1012',159,20 UNION ALL
SELECT 'signature-appetizer-box','Serves 6–8','serves-6-8','VNV-SAB-68',139,10 UNION ALL SELECT 'signature-appetizer-box','Serves 10–12','serves-10-12','VNV-SAB-1012',189,20 UNION ALL
SELECT 'charcuterie-to-go','Serves 6–8','serves-6-8','VNV-CHAR-68',129,10 UNION ALL SELECT 'charcuterie-to-go','Serves 10–12','serves-10-12','VNV-CHAR-1012',179,20 UNION ALL
SELECT 'chicken-chorizo-paella','Serves 6','serves-6','VNV-CCP-6',109,10 UNION ALL SELECT 'chicken-chorizo-paella','Serves 8','serves-8','VNV-CCP-8',139,20 UNION ALL SELECT 'chicken-chorizo-paella','Serves 12','serves-12','VNV-CCP-12',199,30 UNION ALL
SELECT 'seafood-paella','Serves 6','serves-6','VNV-SP-6',129,10 UNION ALL SELECT 'seafood-paella','Serves 8','serves-8','VNV-SP-8',169,20 UNION ALL SELECT 'seafood-paella','Serves 12','serves-12','VNV-SP-12',239,30 UNION ALL
SELECT 'dessert-box','Serves 6–8','serves-6-8','VNV-DB-68',79,10 UNION ALL SELECT 'dessert-box','Serves 10–12','serves-10-12','VNV-DB-1012',119,20 UNION ALL
SELECT 'ensaimada-box','6 Count','6-count','VNV-EB-6',34,10 UNION ALL SELECT 'ensaimada-box','12 Count','12-count','VNV-EB-12',59,20 UNION ALL
SELECT 'thanksgiving-dinner-to-go','Serves 6','serves-6','VNV-TDTG-6',299,10 UNION ALL SELECT 'thanksgiving-dinner-to-go','Serves 8','serves-8','VNV-TDTG-8',389,20 UNION ALL SELECT 'thanksgiving-dinner-to-go','Serves 12','serves-12','VNV-TDTG-12',559,30 UNION ALL
SELECT 'venezuelan-christmas-dinner','Serves 6','serves-6','VNV-VCD-6',299,10 UNION ALL SELECT 'venezuelan-christmas-dinner','Serves 8','serves-8','VNV-VCD-8',389,20 UNION ALL SELECT 'venezuelan-christmas-dinner','Serves 12','serves-12','VNV-VCD-12',549,30 UNION ALL
SELECT 'latin-holiday-dinner','Serves 6','serves-6','VNV-LHD-6',279,10 UNION ALL SELECT 'latin-holiday-dinner','Serves 8','serves-8','VNV-LHD-8',359,20 UNION ALL SELECT 'latin-holiday-dinner','Serves 12','serves-12','VNV-LHD-12',519,30
) v ON p.id_owner=2 AND p.site_key='vnvevents' AND p.slug=v.product_slug LEFT JOIN store_product_variations existing ON existing.id_product=p.id AND existing.slug=v.slug WHERE existing.id IS NULL;

UPDATE store_product_variations existing JOIN store_products p ON p.id=existing.id_product JOIN (
SELECT 'homemade-lasagna-pasticho' ps,'traditional-beef-serves-6' vs,89.00 pr UNION ALL SELECT 'homemade-lasagna-pasticho','traditional-beef-serves-8',119 UNION ALL SELECT 'homemade-lasagna-pasticho','traditional-beef-serves-12',179 UNION ALL SELECT 'homemade-lasagna-pasticho','chicken-serves-6',89 UNION ALL SELECT 'homemade-lasagna-pasticho','chicken-serves-8',119 UNION ALL SELECT 'homemade-lasagna-pasticho','chicken-serves-12',179 UNION ALL SELECT 'homemade-lasagna-pasticho','vegetarian-serves-6',89 UNION ALL SELECT 'homemade-lasagna-pasticho','vegetarian-serves-8',119 UNION ALL SELECT 'homemade-lasagna-pasticho','vegetarian-serves-12',179 UNION ALL SELECT 'latin-bites-box','serves-6-8',109 UNION ALL SELECT 'latin-bites-box','serves-10-12',159 UNION ALL SELECT 'signature-appetizer-box','serves-6-8',139 UNION ALL SELECT 'signature-appetizer-box','serves-10-12',189 UNION ALL SELECT 'charcuterie-to-go','serves-6-8',129 UNION ALL SELECT 'charcuterie-to-go','serves-10-12',179 UNION ALL SELECT 'chicken-chorizo-paella','serves-6',109 UNION ALL SELECT 'chicken-chorizo-paella','serves-8',139 UNION ALL SELECT 'chicken-chorizo-paella','serves-12',199 UNION ALL SELECT 'seafood-paella','serves-6',129 UNION ALL SELECT 'seafood-paella','serves-8',169 UNION ALL SELECT 'seafood-paella','serves-12',239 UNION ALL SELECT 'dessert-box','serves-6-8',79 UNION ALL SELECT 'dessert-box','serves-10-12',119 UNION ALL SELECT 'ensaimada-box','6-count',34 UNION ALL SELECT 'ensaimada-box','12-count',59 UNION ALL SELECT 'thanksgiving-dinner-to-go','serves-6',299 UNION ALL SELECT 'thanksgiving-dinner-to-go','serves-8',389 UNION ALL SELECT 'thanksgiving-dinner-to-go','serves-12',559 UNION ALL SELECT 'venezuelan-christmas-dinner','serves-6',299 UNION ALL SELECT 'venezuelan-christmas-dinner','serves-8',389 UNION ALL SELECT 'venezuelan-christmas-dinner','serves-12',549 UNION ALL SELECT 'latin-holiday-dinner','serves-6',279 UNION ALL SELECT 'latin-holiday-dinner','serves-8',359 UNION ALL SELECT 'latin-holiday-dinner','serves-12',519
) seed ON seed.ps=p.slug AND seed.vs=existing.slug SET existing.price=seed.pr,existing.stock_quantity=999,existing.status='ACTIVE',existing.updated_at=NOW() WHERE p.id_owner=2 AND p.site_key='vnvevents';

-- Category assignment without deleting any existing assignments.
INSERT INTO store_products_categories (id_owner,id_product,id_category)
SELECT 2,p.id,c.id FROM store_products p JOIN store_categories c ON c.id_owner=2 AND c.site_key='vnvevents' AND c.slug=CASE WHEN p.slug='homemade-lasagna-pasticho' THEN 'family-meals' WHEN p.slug IN ('latin-bites-box','signature-appetizer-box','charcuterie-to-go') THEN 'party-boxes' WHEN p.slug IN ('chicken-chorizo-paella','seafood-paella') THEN 'party-trays' WHEN p.slug IN ('dessert-box','ensaimada-box','garlic-bread','salad-add-on','extra-dessert-add-on') THEN 'desserts-add-ons' ELSE 'seasonal-holiday-packages' END LEFT JOIN store_products_categories pc ON pc.id_product=p.id AND pc.id_category=c.id WHERE p.id_owner=2 AND p.site_key='vnvevents' AND p.slug IN ('homemade-lasagna-pasticho','latin-bites-box','signature-appetizer-box','charcuterie-to-go','chicken-chorizo-paella','seafood-paella','dessert-box','ensaimada-box','garlic-bread','salad-add-on','extra-dessert-add-on','thanksgiving-feast','thanksgiving-dinner-to-go','venezuelan-christmas-dinner','latin-holiday-dinner','extra-hallaca','pan-de-jamon','pernil-by-the-pound') AND pc.id IS NULL;

-- Food instructions. Variant pricing represents tray size; Thanksgiving Feast quantity represents guests.
INSERT INTO store_product_food_profiles (id_owner,site_key,id_product,minimum_servings,included_servings,maximum_servings,additional_person_price,preparation_instructions,reheating_instructions,serving_instructions,plating_instructions,presentation_instructions)
SELECT 2,'vnvevents',p.id,CASE WHEN p.slug='thanksgiving-feast' THEN 15 ELSE 1 END,CASE WHEN p.slug='thanksgiving-feast' THEN 15 ELSE 1 END,CASE WHEN p.slug='thanksgiving-feast' THEN NULL ELSE 1 END,0,'Prepared to order. Keep packaging and component labels with the order.','Follow the VNV instructions supplied with the order. Exact reheating needs vary by component.',CASE WHEN p.slug IN ('chicken-chorizo-paella','seafood-paella') THEN 'Serve directly from the premium disposable catering tray or transfer to a presentation platter.' ELSE 'Arrange components for easy service and follow the included VNV guide.' END,'Transfer to serving pieces only when desired.','Keep refrigerated until ready to reheat or serve when applicable.' FROM store_products p WHERE p.id_owner=2 AND p.site_key='vnvevents' AND p.slug IN ('homemade-lasagna-pasticho','latin-bites-box','signature-appetizer-box','charcuterie-to-go','chicken-chorizo-paella','seafood-paella','dessert-box','ensaimada-box','thanksgiving-feast','thanksgiving-dinner-to-go','venezuelan-christmas-dinner','latin-holiday-dinner')
ON DUPLICATE KEY UPDATE minimum_servings=VALUES(minimum_servings),included_servings=VALUES(included_servings),maximum_servings=VALUES(maximum_servings),additional_person_price=VALUES(additional_person_price),preparation_instructions=VALUES(preparation_instructions),reheating_instructions=VALUES(reheating_instructions),serving_instructions=VALUES(serving_instructions),plating_instructions=VALUES(plating_instructions),presentation_instructions=VALUES(presentation_instructions);

-- Optional add-on relationships.
INSERT INTO store_product_relationships (id_owner,site_key,id_product,id_related_product,relationship_type,included_quantity,sort_order,status)
SELECT 2,'vnvevents',parent.id,addon.id,'ADD_ON',0,seed.sort_order,'ACTIVE' FROM (
SELECT 'homemade-lasagna-pasticho' parent_slug,'garlic-bread' addon_slug,10 sort_order UNION ALL SELECT 'homemade-lasagna-pasticho','salad-add-on',20 UNION ALL SELECT 'homemade-lasagna-pasticho','dessert-box',30 UNION ALL SELECT 'chicken-chorizo-paella','salad-add-on',10 UNION ALL SELECT 'chicken-chorizo-paella','dessert-box',20 UNION ALL SELECT 'seafood-paella','salad-add-on',10 UNION ALL SELECT 'seafood-paella','dessert-box',20 UNION ALL SELECT 'latin-bites-box','dessert-box',10 UNION ALL SELECT 'latin-bites-box','ensaimada-box',20 UNION ALL SELECT 'latin-bites-box','charcuterie-to-go',30 UNION ALL SELECT 'signature-appetizer-box','dessert-box',10 UNION ALL SELECT 'signature-appetizer-box','ensaimada-box',20 UNION ALL SELECT 'venezuelan-christmas-dinner','extra-hallaca',10 UNION ALL SELECT 'venezuelan-christmas-dinner','pan-de-jamon',20 UNION ALL SELECT 'venezuelan-christmas-dinner','pernil-by-the-pound',30 UNION ALL SELECT 'latin-holiday-dinner','pan-de-jamon',10 UNION ALL SELECT 'latin-holiday-dinner','pernil-by-the-pound',20
) seed JOIN store_products parent ON parent.id_owner=2 AND parent.site_key='vnvevents' AND parent.slug=seed.parent_slug JOIN store_products addon ON addon.id_owner=2 AND addon.site_key='vnvevents' AND addon.slug=seed.addon_slug
ON DUPLICATE KEY UPDATE sort_order=VALUES(sort_order),status='ACTIVE';

INSERT INTO site_visibility (site_key,entity_type,entity_id,id_user_business,is_visible,visibility_status,notes,created_at,updated_at)
SELECT 'vnvevents','store_product',p.id,2,1,'VISIBLE','VNV Gourmet To Go launch catalog.',NOW(),NOW() FROM store_products p WHERE p.id_owner=2 AND p.site_key='vnvevents' AND p.slug IN ('homemade-lasagna-pasticho','latin-bites-box','signature-appetizer-box','charcuterie-to-go','chicken-chorizo-paella','seafood-paella','dessert-box','ensaimada-box','garlic-bread','salad-add-on','extra-dessert-add-on','thanksgiving-feast','thanksgiving-dinner-to-go','venezuelan-christmas-dinner','latin-holiday-dinner','extra-hallaca','pan-de-jamon','pernil-by-the-pound')
ON DUPLICATE KEY UPDATE id_user_business=2,is_visible=1,visibility_status='VISIBLE',notes=VALUES(notes),updated_at=NOW();

COMMIT;
SELECT 'VNV Gourmet To Go real catalog ready' result;
