CREATE TABLE IF NOT EXISTS `team_member_contracts` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `id_owner` int(11) DEFAULT NULL,
  `team_member_id` int(11) NOT NULL,
  `contract_template_id` int(11) DEFAULT NULL,
  `contract_template_version` varchar(40) DEFAULT NULL,
  `assigned_by` int(11) DEFAULT NULL,
  `validated_by` int(11) DEFAULT NULL,
  `status` varchar(40) NOT NULL DEFAULT 'PENDING',
  `source` varchar(40) DEFAULT NULL,
  `sign_token` varchar(255) DEFAULT NULL,
  `sign_token_expires_at` datetime DEFAULT NULL,
  `sign_token_used_at` datetime DEFAULT NULL,
  `contract_snapshot_html` longtext DEFAULT NULL,
  `contract_snapshot_json` longtext DEFAULT NULL,
  `original_file_path` varchar(255) DEFAULT NULL,
  `signed_file_path` varchar(255) DEFAULT NULL,
  `generated_pdf_path` varchar(255) DEFAULT NULL,
  `signed_pdf_hash` varchar(128) DEFAULT NULL,
  `signature_data` longtext DEFAULT NULL,
  `signature_hash` varchar(128) DEFAULT NULL,
  `signed_ip` varchar(80) DEFAULT NULL,
  `signed_user_agent` text DEFAULT NULL,
  `signed_by_user_id` int(11) DEFAULT NULL,
  `signed_by_email` varchar(160) DEFAULT NULL,
  `signed_at` datetime DEFAULT NULL,
  `validated_at` datetime DEFAULT NULL,
  `uploaded_at` datetime DEFAULT NULL,
  `expires_at` datetime DEFAULT NULL,
  `notes` text DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  `updated_at` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_team_contract_member_owner_status` (`team_member_id`, `id_owner`, `status`),
  KEY `idx_team_contract_token` (`sign_token`),
  KEY `idx_team_contract_owner_status` (`id_owner`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
